export const IS_LOGGED = "IS_LOGGED";
export const RECEIVE_PRODUCTS = "RECEIVE_PRODUCTS";
/* CART ACTIONS */
export const SET_PRODUCT = "SET_PRODUCT";
export const GET_PRODUCT = "GET_PRODUCT";
// export const RECEIVE_PRODUCT = "RECEIVE_PRODUCT";
// export const ADD_TO_PRODUCTS = "ADD_TO_PRODUCTS";
