/* PRODUCTS ACTION */
export const IS_LOGGED = "IS_LOGGED";
export const RECEIVE_PRODUCTS = "RECEIVE_PRODUCTS";
export const RECEIVE_PRODUCT = "RECEIVE_PRODUCT";

/* CART ACTIONS */
export const SET_PRODUCT = "SET_PRODUCT";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const SET_CART = "SET_CART";
export const GET_CART = "GET_CART";
export const SET_COMPLETED_ORDER = "SET_COMPLETED_ORDER";
export const GET_PRODUCTS_COMPLETED_ORDER = "GET_PRODUCTS_COMPLETED_ORDER";
export const LOGIN = "LOGIN";

export const SET_TOTAL = "SET_TOTAL"